dist: trusty

language: node_js

node_js:
  - "12.18.3"

branches:
  only:
    - master

env:
  - EMBER_VERSION=dev

jobs:
  fast_finish: true
  allow_failures:
    - env: EMBER_VERSION=dev

cache:
  npm: false

before_script:
  - npm install -g --silent @angular/cli

script:
  - ng build --prod --output-path docs

notifications:
  email:
    on_failure: change
    on_success: change

before_install:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: dist/poc-angular-tests-unit-e2e
  on:
    branch: master
